### ISSUE TITLE
AttributeError: 'skia.Paint' object has no attribute 'setTextScaleX'

### ISSUE THREAD

**Issue by hyer** [kyamagu/skia-python#223]
**Is your feature request related to a problem? Please describe.**
Is the skia-python library support word spacing (ie. setTextScaleX)? Which is supported in skia c++: [setTextScaleX](https://github.com/google/skia/blob/b7ac9da3e5ac34baf5da70b3e37cdbfd898ed54b/docs/examples/Paint_setTextScaleX.cpp#L6)

**Describe the solution you'd like**
Add the setTextScaleX to python interface.

**Comment by HinTak** [comment]
You didn't notice the `#if 0  // Disabled until updated to use current API.` at the very top? This example has been disabled since Mar 16, 2019 in https://github.com/google/skia/commit/8751512aaadb7bb6c62b191ff8a773db1c53341d, and the actual setTextScaleX was removed two months earlier on Jan 28, 2019 in https://github.com/google/skia/commit/5f528e5fd86c1004e047cdfcd165d7b9798c85ed , and this whole disabled example file was finally removed  last month Nov 10 in https://github.com/google/skia/commit/d06840545bff13146e1e1bd2265965db4166bde9 . 

You are about 4 years too late (Jan 28 2019) asking for this :-).
