### ISSUE TITLE
Mac font is thicker than Linux font

### ISSUE THREAD

**Issue by haoxurt** [kyamagu/skia-python#226]
I use the same code to run separately on Mac and Linux，I found Mac font is thicker than Linux font. The versions are all 87.5.
<img width="1679" alt="image" src="https://github.com/kyamagu/skia-python/assets/43776429/43eb7a68-f4ad-4dc0-b419-1e488612e221">

**Comment by HinTak** [comment]
You mean the same font appears thicker on Mac than on Linux? That's quite understandable - Apple's CoreText process fonts differently than Linux's FreeType, and can be thicker or thinner. If it is about two different fonts (e.g. you just use the "default" typeface) , then it is just different.

Either way, if you want to have the outcome to look exactly the same on mac and on Linux, specify your own font explicitly, and use the new functionality in 120b5:

https://github.com/kyamagu/skia-python/releases/tag/v120.0b5

It was originally introduced just to support fonts not loadable by Apple or Microsoft. On Linux, the "...New_Custom..." call does nothing interesting, since it is just freetype or freetype on Linux and you don't have real alternatives, so it is safe to do that on Linux too.

**Comment by HinTak** [comment]
The default typefaces on mac and on Linux are different, so if you use the "default", it will be different.

**Comment by HinTak** [comment]
Even if you says "Times", "Times" on Linux is not the same font as "Times" on Mac... use your own bundled font file if you want exact same look, plus the new custom call.
