### ISSUE TITLE
python3.7 could not pip install skia-python

### ISSUE THREAD

**Issue by lxomb** [kyamagu/skia-python#247]
ERROR: Could not find a version that satisfies the requirement skia-python (from versions: none)
ERROR: No matching distribution found for skia-python

**Comment by HinTak** [comment]
We haven't changes anything here, other than having released a few 1xx beta's. You should still be able to download a *-87.5-cp37-* wheel from
https://pypi.org/project/skia-python/#files and install that directly, if other method fails.

That said, python 3.7 is already beyond maintenance limit - that's the python foundation's decision. Maybe that's why pypi stops serving pip for older python versions.

Anyway, it is not a problem here. We haven't removed python 3.7 support （yet), although there was a discussion earlier to remove it:
https://github.com/kyamagu/skia-python/blob/59f98a8ae1d40747e9e007f4404109aef093b6c4/.github/workflows/ci.yml#L77

**Comment by HinTak** [comment]
The planned removal of cp37 builds is mainly to speed up build time, and we are not stressed on build time yet.

**Comment by HinTak** [comment]
Python 3.7 was end-of-life 10 months ago: https://devguide.python.org/versions/ you should upgrade soon.

Github has a 6-hour per-job CI limit. Our longest job is under 2 hours so we are not stressed on dropping 3.7 build yet, though it is likely when we add 3.13 or 3.14.
